/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.shapedrawer;

import com.mycompany.vars.varsGetSet;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;

/**
 *
 * @author did
 */
public class inputWindow extends javax.swing.JFrame {

    resultsWin rW = new resultsWin();
    varsGetSet xNY = new varsGetSet();
    int i;
    int x, y;
    int width, height;

    //converting arraylist to array function 
    public static int[] convertIntegers(List<Integer> integers) {
        int[] ret = new int[integers.size()];
        for (int i = 0; i < ret.length; i++) {
            ret[i] = integers.get(i).intValue();
        }
        return ret;
    }

    /**
     * Creates new form inputWindow
     */
    public inputWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        dims1 = new javax.swing.JLabel();
        typeSelectorBox = new javax.swing.JComboBox<>();
        addButtonText1 = new javax.swing.JLabel();
        dims = new javax.swing.JLabel();
        widthText = new javax.swing.JTextField();
        heightText = new javax.swing.JTextField();
        dimsButton = new javax.swing.JButton();
        addButtonText = new javax.swing.JLabel();
        x_get = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        y_get = new javax.swing.JTextField();
        styleSelector = new javax.swing.JComboBox<>();
        resultButton = new javax.swing.JButton();
        resultButtonText = new javax.swing.JLabel();
        dims2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        title.setForeground(new java.awt.Color(0, 153, 153));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Shape Drawer");

        dims1.setText("Shape Type:");

        typeSelectorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select type", "Dot", "Line", "Polygon" }));
        typeSelectorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSelectorBoxActionPerformed(evt);
            }
        });

        addButtonText1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        addButtonText1.setForeground(new java.awt.Color(0, 153, 153));
        addButtonText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addButtonText1.setText("Please press the \"OK\" button after typing width & height");

        dims.setText("Dimensions              :");

        widthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        widthText.setText("width");
        widthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextActionPerformed(evt);
            }
        });

        heightText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        heightText.setText("height");
        heightText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextActionPerformed(evt);
            }
        });

        dimsButton.setText("OK");
        dimsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimsButtonActionPerformed(evt);
            }
        });

        addButtonText.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        addButtonText.setForeground(new java.awt.Color(0, 153, 153));
        addButtonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addButtonText.setText("Please press the \"ADD\" button after every x and y value input");

        x_get.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x_get.setText("X");
        x_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_getActionPerformed(evt);
            }
        });

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        y_get.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y_get.setText("Y");
        y_get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y_getActionPerformed(evt);
            }
        });

        styleSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Style" }));
        styleSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                styleSelectorActionPerformed(evt);
            }
        });

        resultButton.setText("RESULT");
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });

        resultButtonText.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        resultButtonText.setForeground(new java.awt.Color(0, 153, 153));
        resultButtonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultButtonText.setText("To see the result, please press \"RESULT\" button");

        dims2.setText("Shape Style:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(dims, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(dimsButton)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButtonText1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dims2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dims1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                    .addComponent(x_get, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(y_get, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(styleSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeSelectorBox, 0, 213, Short.MAX_VALUE))
                                .addGap(66, 66, 66))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resultButtonText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultButton)
                                .addGap(32, 32, 32)))))
                .addContainerGap())
            .addComponent(addButtonText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButtonText1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dims)
                    .addComponent(widthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButtonText, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dims1)
                    .addComponent(typeSelectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x_get, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(y_get, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dims2)
                    .addComponent(styleSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultButtonText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultButton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeSelectorBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSelectorBoxActionPerformed
        //removing items everytime selected index is changed
        styleSelector.removeAllItems();
        //setting items according to selected index
        if (typeSelectorBox.getSelectedIndex() != 0) {
            switch (typeSelectorBox.getSelectedIndex()) {
                case 1:
                    styleSelector.addItem("Small");
                    styleSelector.addItem("Medium");
                    styleSelector.addItem("Big");
                    break;
                case 2:
                    styleSelector.addItem("Thin");
                    styleSelector.addItem("Bold");
                    styleSelector.addItem("Dashed");
                    break;
                case 3:
                    styleSelector.addItem("Simple");
                    styleSelector.addItem("Colored");
                    styleSelector.addItem("Filled");
                    break;
                default:
                    System.out.println(" ");
            }

        }
    }//GEN-LAST:event_typeSelectorBoxActionPerformed

    private void widthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextActionPerformed

    }//GEN-LAST:event_widthTextActionPerformed

    private void heightTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextActionPerformed

    private void dimsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimsButtonActionPerformed
        //setting size with given values
        width = (Integer.valueOf(widthText.getText()));
        height = (Integer.valueOf(heightText.getText()));
        rW.setSize(width, height);
        rW.setVisible(true);
    }//GEN-LAST:event_dimsButtonActionPerformed

    private void x_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_getActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_getActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //adding x & y values to arraylists
        if (typeSelectorBox.getSelectedIndex() == 1) {
            x = Integer.valueOf(x_get.getText());
            y = Integer.valueOf(y_get.getText());
        }
        int x_value = Integer.valueOf(x_get.getText());
        int y_value = Integer.valueOf(y_get.getText());
        xNY.polyX.add(x_value);
        xNY.polyY.add(y_value);
    }//GEN-LAST:event_addButtonActionPerformed

    private void y_getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y_getActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_y_getActionPerformed

    private void styleSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_styleSelectorActionPerformed

    }//GEN-LAST:event_styleSelectorActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed

        Graphics g = rW.getGraphics();
        Graphics2D g2d = (Graphics2D) g;

        int[] coords_x = convertIntegers(xNY.polyX);
        int[] coords_y = convertIntegers(xNY.polyY);

        if (typeSelectorBox.getSelectedIndex() == 1) {
            switch (styleSelector.getSelectedIndex()) {
                case 0:
                    rW.dotDrawer(g, x, y, 5, 5);
                    break;
                case 1:
                    rW.dotDrawer(g, x, y, 11, 11);
                    break;
                case 2:
                    rW.dotDrawer(g, x, y, 22, 22);
                    break;

            }
        }
        if (typeSelectorBox.getSelectedIndex() == 2) {
            switch (styleSelector.getSelectedIndex()) {
                case 0:
                    rW.tLineDrawer(g, coords_y, coords_y);
                    break;
                case 1:
                    rW.bLineDrawer(g2d, coords_y, coords_y, 25);
                    break;
                case 2:
                    rW.dLineDrawer(g2d, coords_y, coords_y);
                    break;

            }
        }
        if (typeSelectorBox.getSelectedIndex() == 3) {
            switch (styleSelector.getSelectedIndex()) {
                case 0:
                    rW.sPolyDrawer(g, coords_x, coords_y);
                    break;
                case 1:
                    rW.cPolyDrawer(g, coords_x, coords_y);
                    break;
                case 2:
                    rW.fPolyDrawer(g, coords_x, coords_y);
                    break;

            }
        }
        //clearing arraylists for future drawings
        xNY.polyX.clear();
        xNY.polyY.clear();
    }//GEN-LAST:event_resultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addButtonText;
    private javax.swing.JLabel addButtonText1;
    private javax.swing.JLabel dims;
    private javax.swing.JLabel dims1;
    private javax.swing.JLabel dims2;
    private javax.swing.JButton dimsButton;
    public javax.swing.JTextField heightText;
    private javax.swing.JButton resultButton;
    private javax.swing.JLabel resultButtonText;
    private javax.swing.JComboBox<String> styleSelector;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> typeSelectorBox;
    public javax.swing.JTextField widthText;
    private javax.swing.JTextField x_get;
    private javax.swing.JTextField y_get;
    // End of variables declaration//GEN-END:variables
}
