/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.shapedrawer;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Stroke;

/**
 *
 * @author did
 */
public class resultsWin extends javax.swing.JFrame {
    //define polygon
    Polygon poly;


    public resultsWin() {
        initComponents();
        this.setResizable(false);
    }
    
    //simple polygon drawer function
    public void sPolyDrawer(Graphics g, int[] x_values, int[] y_values) {
        poly = new Polygon(x_values, y_values, x_values.length);
        g.drawPolygon(poly);
    }
    
    //coloured polygon drawer function
    public void cPolyDrawer(Graphics g, int[] x_values, int[] y_values) {
        poly = new Polygon(x_values, y_values, x_values.length);
        g.setColor(Color.magenta);
        g.drawPolygon(poly);
    }
    
    //filled polygon drawer function
    public void fPolyDrawer(Graphics g, int[] x_values, int[] y_values) {
        poly = new Polygon(x_values, y_values, x_values.length);
        g.setColor(Color.cyan);
        g.drawPolygon(poly);
        g.fillPolygon(poly);
    }
    
    
    //thin line drawer function
    public void tLineDrawer(Graphics g, int[] x_values, int[] y_values) {
        for (int i = 0; i < x_values.length - 1; i++) {
            g.drawLine(x_values[i], y_values[i], x_values[i + 1], y_values[i + 1]);
        }
    }
    
    //dashed line drawer function
    public void dLineDrawer(Graphics2D g2d, int[] x_values, int[] y_values) {
        for (int i = 0; i < x_values.length - 1; i++) {
            Stroke dashed = new BasicStroke(3, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, new float[]{9}, 0);
            g2d.setStroke(dashed);
            g2d.drawLine(x_values[i], y_values[i], x_values[i+1], y_values[i+1]);
            g2d.dispose();
        }
    }
    //bold line drawer function
    public void bLineDrawer(Graphics2D g2d, int[] x_values, int[] y_values, int thickness) {
        for (int i = 0; i < x_values.length - 1; i++) {
            g2d.setStroke(new BasicStroke(thickness));
            g2d.drawLine(x_values[i], y_values[i], x_values[i + 1], y_values[i + 1]);
        }
    }
    
    
    //dot drawer function
    public void dotDrawer(Graphics g , int x , int y,int width , int length){
        g.fillOval(x, y, width, length);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resultsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resultsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resultsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resultsWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resultsWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
